export const SET_CURRENCY_DETAILS = "SET_CURRENCY_DETAILS";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const SET_DATA = "SET_DATA";
